<?php
/**
 * Implements hook_block_info().
 *
 * This hook declares what blocks are provided by the module.
 */
function mimodulo_block_info() {
  $blocks['mimodulo_bloque_1'] = array(
    'info' => 'Mi bloque numero 1'
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 *
 * This hook generates the contents of the blocks themselves.
 */
function mimodulo_block_view($delta = '') {

	if($delta == 'mimodulo_bloque_1') {
		$block['subject'] = 'Mi Modulo';
		$block['content'] = '<h1>Este es el contenido del bloque</h1>';
	}
  return $block;
}